### ISSUE TITLE
what mean 	<ttl>1440</ttl>

### ISSUE THREAD

**Issue by hosamalzagh** [una/toolsday#37]
what mean 	<ttl>1440</ttl>

**Comment by una** [comment]
can you elaborate?

**Comment by brittharr** [comment]
@hosamalzagh TTL is "time to live" for [RSS feeds](https://validator.w3.org/feed/docs/rss2.html#ltttlgtSubelementOfLtchannelgt), so in this case the feed refreshes after 1440 minutes
